version: "3.9"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - services-network

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    volumes:
      - ./plugins-enabled:/var/www/html/plugins-enabled
    networks:
      - services-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: on-failure
    volumes:
      - ./web-root:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./dhparam:/etc/ssl/certs
      - ./certbot:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - services-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./web-root:/var/www/html
      - ./certbot:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email truongtrongtin0305@gmail.com --agree-tos --no-eff-email --force-renewal -d leave-tracker-api.tintruong.xyz

volumes:
  postgres-data:
    name: postgres-data
networks:
  services-network:
    name: services-network
