version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - services-network

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    volumes:
      - ./plugins-enabled:/var/www/html/plugins-enabled
    networks:
      - services-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: "none" # disable logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - 6379:6379

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: on-failure
  #   volumes:
  #     - ./web-root:/var/www/html
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./dhparam:/etc/ssl/certs
  #     - certbot-etc:/etc/letsencrypt
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - services-network

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./web-root:/var/www/html
  #     - certbot-etc:/etc/letsencrypt
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/html --email truongtrongtin0305@gmail.com --agree-tos --no-eff-email --force-renewal -d leave-tracker-api.tintruong.ga

volumes:
  postgres-data:
    external: true
  # certbot-etc:
  #   external: true
networks:
  services-network:
    external: true
